title: Bastien Rabane
logo: /assets/headshot_circle.png
#description: Ancien directeur d’agence bancaire avec plus de 10 ans d’expérience en front office, je me reconvertis dans la data
pour mettre mes compétences en gestion et en analyse au service de solutions data-driven.
Formé à Python, SQL, Tableau et Power BI, je transforme les données en insights actionnables pour accompagner la
prise de décision stratégique et la transformation digitale des entreprises.
Mon objectif est de devenir un véritable pont entre les besoins opérationnels et les solutions data-driven, grâce à mon sens
de l’analyse, mon adaptabilité, et une approche orientée résultats.
show_downloads: false
theme: jekyll-theme-minimal
